/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.client.view;

import com.mycompany.client.control.RMIClient;
import java.awt.Container;
import java.awt.Dimension;
import java.util.ArrayList;
import com.mycompany.test.student;

/**
 *
 * @author quang
 */
public class seachFrom extends javax.swing.JFrame {

    /**
     * Creates new form seachFrom
     */
    public seachFrom() {
        initComponents();
        jPanelByName = new searchByName();
        jPanelByName.setVisible(false);
        jPanelByGPA = new searchByGPA();
        jPanelByGPA.setVisible(false);
        cl = new RMIClient("127.0.0.1", 8080);
        try {
            stu = cl.getNames();
            for (student s : stu) {
                System.out.println(s);
            }
        } catch (Exception e) {
        }
        try {
            jPanelByName.getStudents(stu);
            jPanelByGPA.getStudents(stu);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chọn nhận viên");

        jButton1.setText("Theo Tên");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Theo GPA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jPanelByName.getParent() != null) {
            // Nếu jPanelByName đã có cha (đã được thêm vào một container khác), hãy xóa nó trước
            Container parent = jPanelByName.getParent();
            parent.remove(jPanelByName);
        }
        if (jPanelByGPA.getParent() != null) {
            // Nếu jPanelByName đã có cha (đã được thêm vào một container khác), hãy xóa nó trước
            Container parent = jPanelByGPA.getParent();
            parent.remove(jPanelByGPA);
        }
        if (jPanelByName.isVisible()) {
            jPanelByName.setVisible(false); // Ẩn JPanel nếu nó đã hiển thị
            this.remove(jPanelByName);
        } else {
            jPanelByName.setBounds(0, 150, 400, 150);
            jPanelByName.setVisible(true); // Hiển thị JPanel nếu nó chưa hiển thị
            this.add(jPanelByName);
        }
        this.revalidate();
        this.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jPanelByGPA.getParent() != null) {
            // Nếu jPanelByName đã có cha (đã được thêm vào một container khác), hãy xóa nó trước
            Container parent = jPanelByGPA.getParent();
            parent.remove(jPanelByGPA);
        }
        if (jPanelByName.getParent() != null) {
            // Nếu jPanelByName đã có cha (đã được thêm vào một container khác), hãy xóa nó trước
            Container parent = jPanelByName.getParent();
            parent.remove(jPanelByName);
        }
        if (jPanelByGPA.isVisible()) {
            jPanelByGPA.setVisible(false); // Ẩn JPanel nếu nó đã hiển thị
            this.remove(jPanelByGPA);
        } else {
            jPanelByGPA.setBounds(0, 150, 400, 150);
            jPanelByGPA.setVisible(true); // Hiển thị JPanel nếu nó chưa hiển thị
            this.add(jPanelByGPA);
        }
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seachFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seachFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seachFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seachFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                seachFrom frame = new seachFrom();
                frame.setSize(400, 600);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private searchByName jPanelByName;
    private searchByGPA jPanelByGPA;
    private RMIClient cl;
    private ArrayList<student> stu;
}
